OP-780 - OH GUI make spring use xxx ACT (rebased)
informatici/openhospital-gui pull request #1334
Opened 2022-10-07 03:50 UTC by goto-eof

2022-10-10 21:18 UTC, mwithi commented on src/main/java/org/isf/admission/gui/AdmissionBrowser.java
> +				admission.setActive(1);
Is this command really needed now?

2022-10-14 14:37 UTC, mwithi requested changes
The PR will not compile after the core merge because more methods have been renamed

2022-10-19 18:56 UTC, goto-eof commented on src/main/java/org/isf/admission/gui/AdmissionBrowser.java
> +				admission.setActive(1);
done

2022-10-19 19:22 UTC, dbmalkovsky commented on src/main/java/org/isf/supplier/gui/SupplierBrowser.java
> +				return sup.getActive().equals(0);
Doesn't `getActive()` return an `int`?   So why isn't the test `return sup.getActive() == 1`?

2022-10-20 15:03 UTC, merged