OP-782 | OPD Chart report to be translated
informatici/openhospital-gui pull request #1947
Opened 2024-01-30 08:05 UTC by loique70

I changed the the string key in the sql request inside the patient_opd_chart.jrxml

2024-01-30 12:08 UTC, dbmalkovsky approved these changes
LGTM

2024-01-31 21:32 UTC, mwithi requested changes
It will not work:
- missing .jasper
- the query should return just the key, and then translated within JasperReport
- remove all "KEY" from keys, they are unneded

please check my messages on Slack, thanks!

2024-02-02 09:27 UTC, mwithi commented on rpt_base/.gitignore
please revert this change

2024-02-02 09:28 UTC, mwithi commented on rpt_base/patient_clinical_sheet_patsubreport.jasper
please, despite the subreport is recompiled automatically, revert this change

2024-02-02 09:29 UTC, mwithi commented on DataAdapter.jrdax
Please don't push this file

2024-02-02 11:04 UTC, dbmalkovsky commented on rpt_base/patient_opd_chart.jrxml
> +				<textFieldExpression><![CDATA[$F{FIELD}]]></textFieldExpression>
is this statement even needed given the removal of the concatenation?

2024-02-02 11:04 UTC, dbmalkovsky commented on rpt_base/patient_opd_chart.properties
> +IdKEY = ID
should this have a colon like the other strings?

2024-02-02 14:00 UTC, merged