OP-655 Use interface instead of concreate class
informatici/openhospital-gui pull request #882
Opened 2021-09-14 12:58 UTC by dbmalkovsky

See OP-655

As usual some formatting is included

2021-09-16 21:10 UTC, mwithi requested changes
Small changes required

2021-09-16 21:10 UTC, mwithi commented on src/main/java/org/isf/lab/gui/LabNew.java
> +				List<ExamRow> exaRowArray;
indentation problem

2021-09-16 21:10 UTC, mwithi commented on src/main/java/org/isf/opd/gui/OpdEdit.java
> +	            List<Disease> diseasesOPD = null;
indentation problem

2021-09-16 21:10 UTC, mwithi commented on src/main/java/org/isf/opd/gui/OpdEdit.java
> +	            List<Disease> diseasesOPD = null;
intendation problem?

2021-09-16 21:10 UTC, mwithi commented on src/main/java/org/isf/priceslist/gui/PricesBrowser.java
> +    private List<Exam> examArray;
indentation problem?

2021-09-17 06:57 UTC, dbmalkovsky commented on src/main/java/org/isf/lab/gui/LabNew.java
> +				List<ExamRow> exaRowArray;
Fixed

2021-09-17 06:57 UTC, dbmalkovsky commented on src/main/java/org/isf/opd/gui/OpdEdit.java
> +	            List<Disease> diseasesOPD = null;
Fixed

2021-09-17 06:57 UTC, dbmalkovsky commented on src/main/java/org/isf/opd/gui/OpdEdit.java
> +	            List<Disease> diseasesOPD = null;
Fixed

2021-09-17 06:58 UTC, dbmalkovsky commented on src/main/java/org/isf/priceslist/gui/PricesBrowser.java
> +    private List<Exam> examArray;
Fixed

2021-09-17 07:14 UTC, mwithi approved these changes

2021-09-17 07:19 UTC, merged